site_name: Electron Workshop
site_url: http://electronworkshop.com.au
theme:
  name: material
  logo: assets/Electron-Workshop-logo.png
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.higlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  language: en
  palette:
    scheme: slate
    primary: white
    accent: black
extra_css:
  - assets/css/customizations.css
  - https://unpkg.com/leaflet@1.3.1/dist/leaflet.css
plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - ezlinks:
      wikilinks: true
  - blog:
      post_excerpt: required
      archive: true
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  - tags
extra_javascript:
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
#   - https://raw.githubusercontent.com/calvinmetcalf/leaflet-ajax/master/dist/leaflet.ajax.min.js
  